"""SOTA-watch source: ``~/Repos/sota-watch/proposals/*.md`` → records.

Records-shaped (one Record per proposal file — units-of-work ontology,
like GitHub PRs/issues and the sibling ``research`` source). Local-file
source, self-generated by the sota-watch cron job that flags where the
stack lags state-of-the-art. No export ritual, the timer can hit it
directly.

Unlike ``research_reports``, there is NO ``_quarantine/`` guard here:
proposals are produced by the owner's own tooling, not scanned untrusted
input, so the top-level-only glob is sufficient. Bodies are ingested
verbatim; the store scrubs secrets on write and the MCP layer wraps
responses on return.
"""
from __future__ import annotations

import logging
import os
from collections.abc import Iterator
from datetime import UTC, datetime
from pathlib import Path

from aggregator.sources.base import IngestResult, Record, stable_id_for

log = logging.getLogger(__name__)

# Only scan this many leading lines for the first ``# `` heading; a proposal
# without an early H1 falls back to its filename stem (yyyy-mm-dd-slug).
HEADING_SCAN_LINES = 50

DEFAULT_PROPOSALS_DIR = "~/Repos/sota-watch/proposals"


def _first_heading(text: str) -> str | None:
    """Return the first ``# `` heading within the leading scan window,
    stripped of leading ``#`` marks and surrounding whitespace."""
    for line in text.splitlines()[:HEADING_SCAN_LINES]:
        if line.startswith("# "):
            return line.lstrip("#").strip()
    return None


class SotaWatchSource:
    """Source implementation for sota-watch proposals."""

    name = "sota-watch"

    def rebuild_input(self) -> str:
        """``sources.base.SupportsRebuild`` — why ``--rebuild`` is allowed here.

        The proposals directory is written by sota-watch on this machine and
        every stored row comes from a file still in it, so a re-scan reproduces
        the whole population the DELETE can reach.
        """
        return (
            "the sota-watch proposals directory on this machine, which "
            "sota-watch itself writes and keeps"
        )

    def __init__(self, proposals_dir: str | os.PathLike[str] | None = None):
        self.proposals_dir = Path(
            proposals_dir
            or os.environ.get("AGGREGATOR_SOTA_WATCH_DIR")
            or os.path.expanduser(DEFAULT_PROPOSALS_DIR)
        )

    def record_shape(self) -> dict[str, str]:
        """DSL-facing field surface (M2 help generator)."""
        return {
            "subject": "str (first markdown heading, or proposal stem)",
            "body": "str (full proposal markdown)",
            "path": "str (source file path)",
        }

    def _proposal_to_record(
        self, path: Path, mtime: datetime, text: str
    ) -> Record:
        subject = _first_heading(text) or path.stem
        return Record(
            stable_id=stable_id_for(self.name, path.stem),
            source=self.name,
            subject=subject,
            body=text,
            tags=["sota-watch"],
            created_at=mtime,
            updated_at=mtime,
            extra={"path": str(path)},
        )

    def iter_records(
        self,
        since: datetime | None,
        errors: list[str] | None = None,
    ) -> Iterator[Record]:
        """Yield one Record per top-level ``*.md`` proposal.

        ``since``: skip files whose mtime <= since (naive ``since`` treated
        as UTC, matching the CLI's ``--since`` stamping). Unreadable files
        are appended to the ``errors`` sink and skipped — partial ingest
        beats total loss (same policy as the github + research sources).
        Decode never hard-fails: proposals are UTF-8, read with
        ``errors='replace'`` so stray bytes degrade to replacement chars
        instead of crashing.
        """
        since_utc: datetime | None = None
        if since is not None:
            since_utc = (
                since if since.tzinfo is not None else since.replace(tzinfo=UTC)
            )

        for path in sorted(self.proposals_dir.glob("*.md")):
            try:
                mtime = datetime.fromtimestamp(path.stat().st_mtime, tz=UTC)
            except OSError as e:
                log.warning("stat failed for %s: %s", path, e)
                if errors is not None:
                    errors.append(f"{path}: stat failed: {e}")
                continue
            if since_utc is not None and mtime <= since_utc:
                continue
            try:
                text = path.read_text(encoding="utf-8", errors="replace")
            except OSError as e:
                log.warning("read failed for %s: %s", path, e)
                if errors is not None:
                    errors.append(f"{path}: read failed: {e}")
                continue
            yield self._proposal_to_record(path, mtime, text)

    def ingest(self, since: datetime | None) -> IngestResult:
        """Count-only path for protocol compat; persistence is the CLI's job."""
        errors: list[str] = []
        added = sum(1 for _ in self.iter_records(since, errors=errors))
        return IngestResult(added=added, updated=0, skipped=0, errors=errors)
